### ISSUE TITLE
Button css and Body code

### ISSUE THREAD

**Issue by AlexanderTahtadjian** [AlexanderTahtadjian/modularity-mindfulness#1]
@hellachella

I placed some css code to style my button but for some reason its not applying. Also for the body copy, is the Japanese and English text together, or are they separate parts?
![Screenshot 2020-09-27 172626](https://user-images.githubusercontent.com/55193211/94376135-9f4c7c00-00e6-11eb-8e95-618af49216f1.jpg)

**Comment by hellachella** [comment]
See the comment I left in your other issue first.

**Comment by AlexanderTahtadjian** [comment]
ok I will
