### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by AlexanderTahtadjian** [AlexanderTahtadjian/modularity-mindfulness#3]
@mackenzierose
@JessJodoin
I placed some code for my buttons but for some reason its not applying it

**Comment by MacKenzieRose** [comment]
Hey!

So your code is actually applying styling to your buttons (for example, `text-decoration` and `color` have changed).  If you specify a `border-style` you'll see your button borders too.

Re-tag me if you need more help 😄

**Comment by AlexanderTahtadjian** [comment]
thanks
